version: '3'

services:

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fastapi
    command: uvicorn --host 0.0.0.0 --port 8000 main:app --reload
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    networks:
      - fastapi-network
    restart: always

networks:
  fastapi-network:
    driver: bridge